### ISSUE TITLE
Dependency on forked model

### ISSUE THREAD

**Issue by StefPac** [justjake/Gauss#2]
Thank you so much for building this and sharing it with the world! I wanted to ask whether it is absolutely necessary to depend on your fork of the model, which adds maintenance burden to  you or gets obsolete perhaps quickly. Cheers!

**Comment by justjake** [comment]
The fork has very minor changes that may already be fixed upstream at this point:

1. Using a correct type for the seed to avoid overflow panic. 
2. Making image batch size a per-batch option instead of a per-pipeline option. 

It should be trivial to use upstream if/when fixes for those issues are merged there.

**Comment by justjake** [comment]
Yep, it looks like upstream has fixed all the issues, so I'll switch over to that.
